In [39]:
import random
import pandas as pd
import numpy as np

In [40]:
list_SNP = [0,1,2]
SNP1 = random.choices(list_SNP,k=500)
SNP2 = random.choices(list_SNP,k=500)
SNP3 = random.choices(list_SNP,k=500)
SNP4 = random.choices(list_SNP,k=500)
SNP5 = random.choices(list_SNP,k=500)

In [41]:
dict = {'SNP1': SNP1, 'SNP2': SNP2, 'SNP3': SNP3, 'SNP4':SNP4, 'SNP5':SNP5} 
    
df = pd.DataFrame(dict)

In [42]:
print(df)

     SNP1  SNP2  SNP3  SNP4  SNP5
0       1     0     0     0     0
1       0     2     0     0     2
2       2     1     0     1     0
3       1     0     0     0     2
4       1     0     0     2     1
..    ...   ...   ...   ...   ...
495     2     2     1     0     0
496     2     1     1     0     2
497     1     2     1     0     1
498     0     0     0     2     1
499     2     2     1     1     0

[500 rows x 5 columns]

In [44]:
list_gene = ['gene_exp_val_1','gene_exp_val_2','gene_exp_val_3','gene_exp_val_4','gene_exp_val_5','gene_exp_val_6','gene_exp_val_7','gene_exp_val_8','gene_exp_val_9','gene_exp_val_10']
for index in range(0,10):
    gene_list = [None] * 500
    for i in range(0,500):
        gene_mean = random.randint(2,8)
        gene_std = random.randint(10,20)/10
        gene_expr = np.random.normal(gene_mean, gene_std)
        gene_list[i] = gene_expr
    df[list_gene[index]] = gene_list

In [33]:
df[list_gene[8]]

0      6.786610
1      4.052540
2      5.160760
3      3.924883
4      4.991990
         ...
495    4.342526
496    5.091386
497    6.532135
498    4.199163
499         NaN
Name: gene_exp_val_9gene_exp_val_10, Length: 500, dtype: float64

In [45]:
print(df)

     SNP1  SNP2  SNP3  SNP4  SNP5  gene_exp_val_1  gene_exp_val_2  \
0       1     0     0     0     0        4.296752        5.879217
1       0     2     0     0     2        7.368011        4.092037
2       2     1     0     1     0        1.844377        6.882229
3       1     0     0     0     2        9.238597       -0.471397
4       1     0     0     2     1        6.551229        7.677021
..    ...   ...   ...   ...   ...             ...             ...
495     2     2     1     0     0        5.235465        1.393969
496     2     1     1     0     2        1.623699        6.256417
497     1     2     1     0     1        9.792995        3.661113
498     0     0     0     2     1        4.153709        3.302666
499     2     2     1     1     0        3.681540        5.368378

     gene_exp_val_3  gene_exp_val_4  gene_exp_val_5  gene_exp_val_6  \
0          3.949851        4.894200        4.661799       10.071671
1          4.209129        4.547342        5.929115        6.492243
2          7.523441       -0.068827        6.639973        0.465988
3          3.408929        3.683813        3.437724        6.491071
4          2.313837        8.811369        1.636475        2.588912
..              ...             ...             ...             ...
495        4.369399        2.129717        2.731188        0.745589
496        3.854754        3.533750        6.780918        6.398148
497        6.462687        7.776345        3.278449        7.002370
498        1.473132        8.468855        6.964625        6.907675
499        3.468077        6.687554        3.991590        0.965127

     gene_exp_val_7  gene_exp_val_8  gene_exp_val_9  gene_exp_val_10
0          1.192632        3.388680        4.825220         4.646826
1          2.122355        4.519574        6.296642         3.181311
2          8.669607        6.191680        7.097006         1.793464
3          1.820360        1.899660        1.721532         5.760226
4          2.936327        1.527553        2.728626         0.233581
..              ...             ...             ...              ...
495        1.641429        4.324472        6.862823         7.703731
496        5.115951        4.370081        2.905870         4.195917
497        1.445182        6.053091        4.603172         2.471545
498        5.199383        6.255936        2.935148         7.588588
499        3.489906        9.444907        5.318024         6.103231

[500 rows x 15 columns]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498